baseurl      = "https://epons.tech"
title        = "Elena Pons | Technical Writer"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = 'Technical Writer'
homeSubtitleUrl = '/portfolio'

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

# Metadata mostly used in document's head
description = "Elena Pons | Technical Writer"
keywords = "portfolio"
images = [""]

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[languages]
[languages.en]
title = 'Elena Pons'
keywords = "portfolio"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

[languages.en.params]
subtitle  = '<a href="/portfolio">Technical Writer</a>'

[languages.en.params.logo]
logoText = "Elena Pons"
logoHomeLink = "/"
logoMark     = "="

# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "about"
name       = "About Me"
url        = "/about"

[[menu.main]]
identifier = "portfolio"
name       = "Portfolio"
url        = "/portfolio"
weight = 2

[[params.social]]
name = "github"
url  = "https://github.com/elenapons"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/elena-pons-28926aa1"


[[params.social]]
name = "email"
url  = "mailto:eponsc@gmail.com"

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true